DROP TABLE IF EXISTS `Galacticus_test`;
CREATE TABLE `Galacticus_test` (
snapnum SMALLINT NOT NULL,
scale DOUBLE NOT NULL,
NInFileSnapnum BIGINT NOT NULL,
fileNum INTEGER NOT NULL,
forestId BIGINT NULL, 
phkey BIGINT NULL, 
Mvir_SAM DOUBLE NOT NULL,
McoldDisk DOUBLE NOT NULL,
MstarDisk DOUBLE NOT NULL,
Rdisk DOUBLE  NOT NULL,
x DOUBLE NOT NULL,
y DOUBLE NOT NULL,
z DOUBLE NOT NULL,
LstarSDSSg DOUBLE NOT NULL
) ENGINE=MyISAM;
